version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: django_blog
       MYSQL_PASSWORD: admin
       MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '127.0.0.1:3306:3306'

volumes:
  db_data:
