# Generated by Django 3.0.2 on 2020-07-25 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chart_type',
            field=models.CharField(default='piechart', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Should post be public?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
